PRODUCTS_DATA = [
    # Silver Grills (10 products)
    {
        "name": "Silver Single Tooth Grill",
        "slug": "silver-single-tooth-grill",
        "category": "silver-grills",
        "price": 2499,
        "description": "Premium sterling silver single tooth grill for a subtle statement",
        "images": ["/silver-grills/grill-1.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 1,
        "finish": "Polished",
        "stock": 25,
        "rating": 4.8,
        "reviews_count": 42,
        "tags": ["silver", "single", "minimal"],
        "featured": True,
        "bestseller": True
    },
    {
        "name": "Sterling Smile Grill",
        "slug": "sterling-smile-grill",
        "category": "silver-grills",
        "price": 2999,
        "description": "Classic two-tooth sterling silver grill with mirror finish",
        "images": ["/silver-grills/grill-2.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 2,
        "finish": "Mirror",
        "stock": 30,
        "rating": 4.9,
        "reviews_count": 38,
        "tags": ["silver", "classic"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Silver Fang Grill",
        "slug": "silver-fang-grill",
        "category": "silver-grills",
        "price": 3499,
        "description": "Edgy fang-style silver grill for bold statement",
        "images": ["/silver-grills/grill-3.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 2,
        "finish": "Matte",
        "stock": 20,
        "rating": 4.7,
        "reviews_count": 28,
        "tags": ["silver", "fang", "edgy"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Urban Silver Grill",
        "slug": "urban-silver-grill",
        "category": "silver-grills",
        "price": 3999,
        "description": "Modern urban design silver grill with textured finish",
        "images": ["/silver-grills/grill-4.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 3,
        "finish": "Textured",
        "stock": 18,
        "rating": 4.6,
        "reviews_count": 22,
        "tags": ["silver", "urban", "modern"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Twin Silver Grill",
        "slug": "twin-silver-grill",
        "category": "silver-grills",
        "price": 4499,
        "description": "Symmetrical twin tooth silver grill set",
        "images": ["/silver-grills/grill-5.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 4,
        "finish": "Polished",
        "stock": 22,
        "rating": 4.8,
        "reviews_count": 31,
        "tags": ["silver", "twin", "symmetrical"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Classic 4-Tooth Grill",
        "slug": "classic-4-tooth-grill",
        "category": "silver-grills",
        "price": 5999,
        "description": "Traditional four-tooth sterling silver grill",
        "images": ["/silver-grills/grill-6.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 4,
        "finish": "Mirror",
        "stock": 15,
        "rating": 4.9,
        "reviews_count": 45,
        "tags": ["silver", "classic"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Premium Silver Row",
        "slug": "premium-silver-row",
        "category": "silver-grills",
        "price": 6499,
        "description": "Full front row premium silver grill",
        "images": ["/silver-grills/grill-7.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 6,
        "finish": "Polished",
        "stock": 12,
        "rating": 4.7,
        "reviews_count": 19,
        "tags": ["silver", "premium", "full-row"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Silver Luxe Grill",
        "slug": "silver-luxe-grill",
        "category": "silver-grills",
        "price": 6999,
        "description": "Luxury silver grill with intricate detailing",
        "images": ["/silver-grills/grill-8.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 6,
        "finish": "Brushed",
        "stock": 10,
        "rating": 4.8,
        "reviews_count": 24,
        "tags": ["silver", "luxury"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Silver Elite Set",
        "slug": "silver-elite-set",
        "category": "silver-grills",
        "price": 7999,
        "description": "Complete top and bottom silver grill set",
        "images": ["/silver-grills/grill-9.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 8,
        "finish": "Mirror",
        "stock": 8,
        "rating": 4.9,
        "reviews_count": 16,
        "tags": ["silver", "elite", "set"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Signature Silver Crown",
        "slug": "signature-silver-crown",
        "category": "silver-grills",
        "price": 8999,
        "description": "Premium signature silver crown design",
        "images": ["/silver-grills/grill-10.jpg"],
        "material": "Sterling Silver",
        "teeth_count": 8,
        "finish": "Polished",
        "stock": 5,
        "rating": 5.0,
        "reviews_count": 12,
        "tags": ["silver", "signature", "crown"],
        "featured": True,
        "bestseller": False
    },
    
    # Gold Grills (10 products)
    {
        "name": "Gold Single Grill",
        "slug": "gold-single-grill",
        "category": "gold-grills",
        "price": 4999,
        "description": "18K gold plated single tooth grill",
        "images": ["/gold-grills/grill-1.jpg"],
        "material": "18K Gold",
        "teeth_count": 1,
        "finish": "Polished",
        "stock": 20,
        "rating": 4.9,
        "reviews_count": 55,
        "tags": ["gold", "single", "18k"],
        "featured": True,
        "bestseller": True
    },
    {
        "name": "18K Shine Grill",
        "slug": "18k-shine-grill",
        "category": "gold-grills",
        "price": 5999,
        "description": "Brilliant shine 18K gold two-tooth grill",
        "images": ["/gold-grills/grill-2.jpg"],
        "material": "18K Gold",
        "teeth_count": 2,
        "finish": "High Polish",
        "stock": 18,
        "rating": 4.8,
        "reviews_count": 47,
        "tags": ["gold", "shine", "18k"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Royal Gold Fang",
        "slug": "royal-gold-fang",
        "category": "gold-grills",
        "price": 6999,
        "description": "Royal fang design in pure gold finish",
        "images": ["/gold-grills/grill-3.jpg"],
        "material": "18K Gold",
        "teeth_count": 2,
        "finish": "Matte Gold",
        "stock": 15,
        "rating": 4.7,
        "reviews_count": 33,
        "tags": ["gold", "fang", "royal"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Luxe Gold Bite",
        "slug": "luxe-gold-bite",
        "category": "gold-grills",
        "price": 7999,
        "description": "Luxury gold grill with premium craftsmanship",
        "images": ["/gold-grills/grill-4.jpg"],
        "material": "18K Gold",
        "teeth_count": 3,
        "finish": "Brushed",
        "stock": 14,
        "rating": 4.9,
        "reviews_count": 29,
        "tags": ["gold", "luxury"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Gold Twin Grill",
        "slug": "gold-twin-grill",
        "category": "gold-grills",
        "price": 8999,
        "description": "Matching twin gold grills for perfect symmetry",
        "images": ["/gold-grills/grill-5.jpg"],
        "material": "18K Gold",
        "teeth_count": 4,
        "finish": "Polished",
        "stock": 12,
        "rating": 4.8,
        "reviews_count": 38,
        "tags": ["gold", "twin"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Classic Gold Row",
        "slug": "classic-gold-row",
        "category": "gold-grills",
        "price": 9999,
        "description": "Classic four-tooth gold row grill",
        "images": ["/gold-grills/grill-6.jpg"],
        "material": "18K Gold",
        "teeth_count": 4,
        "finish": "Mirror",
        "stock": 10,
        "rating": 5.0,
        "reviews_count": 52,
        "tags": ["gold", "classic"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Premium Gold Set",
        "slug": "premium-gold-set",
        "category": "gold-grills",
        "price": 11999,
        "description": "Premium six-tooth gold grill set",
        "images": ["/gold-grills/grill-7.jpg"],
        "material": "18K Gold",
        "teeth_count": 6,
        "finish": "Polished",
        "stock": 8,
        "rating": 4.9,
        "reviews_count": 26,
        "tags": ["gold", "premium"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Gold Supreme Grill",
        "slug": "gold-supreme-grill",
        "category": "gold-grills",
        "price": 13999,
        "description": "Supreme quality gold grill with superior finish",
        "images": ["/gold-grills/grill-8.jpg"],
        "material": "18K Gold",
        "teeth_count": 6,
        "finish": "High Polish",
        "stock": 7,
        "rating": 4.8,
        "reviews_count": 21,
        "tags": ["gold", "supreme"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Royal Gold Elite",
        "slug": "royal-gold-elite",
        "category": "gold-grills",
        "price": 15999,
        "description": "Elite royal gold grill with intricate design",
        "images": ["/gold-grills/grill-9.jpg"],
        "material": "18K Gold",
        "teeth_count": 8,
        "finish": "Brushed Gold",
        "stock": 6,
        "rating": 4.9,
        "reviews_count": 18,
        "tags": ["gold", "royal", "elite"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Gold Legacy Crown",
        "slug": "gold-legacy-crown",
        "category": "gold-grills",
        "price": 17999,
        "description": "Legacy crown design in premium 18K gold",
        "images": ["/gold-grills/grill-10.jpg"],
        "material": "18K Gold",
        "teeth_count": 8,
        "finish": "Mirror",
        "stock": 5,
        "rating": 5.0,
        "reviews_count": 14,
        "tags": ["gold", "legacy", "crown"],
        "featured": True,
        "bestseller": False
    },
    
    # Diamond Grills (10 products)
    {
        "name": "Diamond Spark Grill",
        "slug": "diamond-spark-grill",
        "category": "diamond-grills",
        "price": 9999,
        "description": "Single tooth with diamond sparkle accent",
        "images": ["/diamond-grills/grill-1.jpg"],
        "material": "18K Gold",
        "teeth_count": 1,
        "gem_type": "Diamond",
        "finish": "Polished",
        "stock": 15,
        "rating": 4.9,
        "reviews_count": 64,
        "tags": ["diamond", "luxury", "sparkle"],
        "featured": True,
        "bestseller": True
    },
    {
        "name": "Diamond Cut Smile",
        "slug": "diamond-cut-smile",
        "category": "diamond-grills",
        "price": 12999,
        "description": "Precision cut diamonds on gold base",
        "images": ["/diamond-grills/grill-2.jpg"],
        "material": "18K Gold",
        "teeth_count": 2,
        "gem_type": "Diamond",
        "finish": "High Polish",
        "stock": 12,
        "rating": 4.8,
        "reviews_count": 58,
        "tags": ["diamond", "precision"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Ice Diamond Grill",
        "slug": "ice-diamond-grill",
        "category": "diamond-grills",
        "price": 14999,
        "description": "Iced out with premium micro diamonds",
        "images": ["/diamond-grills/grill-3.jpg"],
        "material": "18K Gold",
        "teeth_count": 2,
        "gem_type": "Diamond",
        "finish": "Iced",
        "stock": 10,
        "rating": 5.0,
        "reviews_count": 43,
        "tags": ["diamond", "iced"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Diamond Luxe Row",
        "slug": "diamond-luxe-row",
        "category": "diamond-grills",
        "price": 16999,
        "description": "Luxury diamond row with flawless stones",
        "images": ["/diamond-grills/grill-4.jpg"],
        "material": "18K Gold",
        "teeth_count": 4,
        "gem_type": "Diamond",
        "finish": "Mirror",
        "stock": 8,
        "rating": 4.9,
        "reviews_count": 37,
        "tags": ["diamond", "luxury", "row"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Diamond Drip Grill",
        "slug": "diamond-drip-grill",
        "category": "diamond-grills",
        "price": 18999,
        "description": "Cascading diamond design for maximum impact",
        "images": ["/diamond-grills/grill-5.jpg"],
        "material": "18K Gold",
        "teeth_count": 4,
        "gem_type": "Diamond",
        "finish": "Polished",
        "stock": 7,
        "rating": 4.8,
        "reviews_count": 31,
        "tags": ["diamond", "drip"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Diamond Elite Set",
        "slug": "diamond-elite-set",
        "category": "diamond-grills",
        "price": 21999,
        "description": "Elite diamond grill set with premium stones",
        "images": ["/diamond-grills/grill-6.jpg"],
        "material": "18K Gold",
        "teeth_count": 6,
        "gem_type": "Diamond",
        "finish": "High Polish",
        "stock": 6,
        "rating": 4.9,
        "reviews_count": 28,
        "tags": ["diamond", "elite", "set"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Diamond Royal Smile",
        "slug": "diamond-royal-smile",
        "category": "diamond-grills",
        "price": 24999,
        "description": "Royal design with VVS diamonds",
        "images": ["/diamond-grills/grill-7.jpg"],
        "material": "18K Gold",
        "teeth_count": 6,
        "gem_type": "VVS Diamond",
        "finish": "Mirror",
        "stock": 5,
        "rating": 5.0,
        "reviews_count": 22,
        "tags": ["diamond", "royal", "vvs"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Diamond Crown Grill",
        "slug": "diamond-crown-grill",
        "category": "diamond-grills",
        "price": 27999,
        "description": "Crown design with flawless diamonds",
        "images": ["/diamond-grills/grill-8.jpg"],
        "material": "18K Gold",
        "teeth_count": 8,
        "gem_type": "Flawless Diamond",
        "finish": "Polished",
        "stock": 4,
        "rating": 4.9,
        "reviews_count": 19,
        "tags": ["diamond", "crown"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Diamond Emperor Grill",
        "slug": "diamond-emperor-grill",
        "category": "diamond-grills",
        "price": 32999,
        "description": "Emperor class full diamond grill",
        "images": ["/diamond-grills/grill-9.jpg"],
        "material": "18K Gold",
        "teeth_count": 8,
        "gem_type": "VVS Diamond",
        "finish": "High Polish",
        "stock": 3,
        "rating": 5.0,
        "reviews_count": 15,
        "tags": ["diamond", "emperor", "premium"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Diamond Infinity Grill",
        "slug": "diamond-infinity-grill",
        "category": "diamond-grills",
        "price": 39999,
        "description": "Ultimate infinity design with premium diamonds",
        "images": ["/diamond-grills/grill-10.jpg"],
        "material": "18K Gold",
        "teeth_count": 10,
        "gem_type": "Flawless Diamond",
        "finish": "Mirror",
        "stock": 2,
        "rating": 5.0,
        "reviews_count": 11,
        "tags": ["diamond", "infinity", "ultimate"],
        "featured": True,
        "bestseller": False
    },
    
    # Iced Out Grills (10 products)
    {
        "name": "Ice Single Grill",
        "slug": "ice-single-grill",
        "category": "iced-out-grills",
        "price": 14999,
        "description": "Fully iced single tooth with CZ stones",
        "images": ["https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"],
        "material": "18K Gold",
        "teeth_count": 1,
        "gem_type": "CZ Stones",
        "finish": "Iced",
        "stock": 12,
        "rating": 4.8,
        "reviews_count": 72,
        "tags": ["iced", "cz", "single"],
        "featured": True,
        "bestseller": True
    },
    {
        "name": "Ice Twin Grill",
        "slug": "ice-twin-grill",
        "category": "iced-out-grills",
        "price": 17999,
        "description": "Twin iced grills with maximum shine",
        "images": ["https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"],
        "material": "18K Gold",
        "teeth_count": 2,
        "gem_type": "CZ Stones",
        "finish": "Iced",
        "stock": 10,
        "rating": 4.9,
        "reviews_count": 68,
        "tags": ["iced", "twin"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Ice Drip Row",
        "slug": "ice-drip-row",
        "category": "iced-out-grills",
        "price": 19999,
        "description": "Full row iced out drip design",
        "images": ["https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"],
        "material": "18K Gold",
        "teeth_count": 4,
        "gem_type": "CZ Stones",
        "finish": "Iced",
        "stock": 9,
        "rating": 4.7,
        "reviews_count": 54,
        "tags": ["iced", "drip"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Frozen Smile Grill",
        "slug": "frozen-smile-grill",
        "category": "iced-out-grills",
        "price": 22999,
        "description": "Completely frozen design with micro pavé",
        "images": ["https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"],
        "material": "18K Gold",
        "teeth_count": 4,
        "gem_type": "Micro Pavé CZ",
        "finish": "Iced",
        "stock": 8,
        "rating": 4.8,
        "reviews_count": 47,
        "tags": ["iced", "frozen", "pave"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Ice Luxe Grill",
        "slug": "ice-luxe-grill",
        "category": "iced-out-grills",
        "price": 24999,
        "description": "Luxury iced grill with premium stone setting",
        "images": ["https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"],
        "material": "18K Gold",
        "teeth_count": 6,
        "gem_type": "Premium CZ",
        "finish": "Iced",
        "stock": 7,
        "rating": 4.9,
        "reviews_count": 41,
        "tags": ["iced", "luxury"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Iced Out Elite",
        "slug": "iced-out-elite",
        "category": "iced-out-grills",
        "price": 28999,
        "description": "Elite fully iced grill with flawless setting",
        "images": ["https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"],
        "material": "18K Gold",
        "teeth_count": 6,
        "gem_type": "Premium CZ",
        "finish": "Iced",
        "stock": 6,
        "rating": 4.8,
        "reviews_count": 36,
        "tags": ["iced", "elite"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Crystal Frost Grill",
        "slug": "crystal-frost-grill",
        "category": "iced-out-grills",
        "price": 31999,
        "description": "Crystal frost design with brilliant shine",
        "images": ["https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"],
        "material": "18K Gold",
        "teeth_count": 8,
        "gem_type": "Crystal CZ",
        "finish": "Iced",
        "stock": 5,
        "rating": 4.9,
        "reviews_count": 29,
        "tags": ["iced", "crystal", "frost"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Glacier Crown Grill",
        "slug": "glacier-crown-grill",
        "category": "iced-out-grills",
        "price": 34999,
        "description": "Glacier crown with complete ice coverage",
        "images": ["https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"],
        "material": "18K Gold",
        "teeth_count": 8,
        "gem_type": "Premium CZ",
        "finish": "Iced",
        "stock": 4,
        "rating": 5.0,
        "reviews_count": 24,
        "tags": ["iced", "glacier", "crown"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Arctic Shine Grill",
        "slug": "arctic-shine-grill",
        "category": "iced-out-grills",
        "price": 39999,
        "description": "Arctic inspired fully iced masterpiece",
        "images": ["https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"],
        "material": "18K Gold",
        "teeth_count": 10,
        "gem_type": "Premium CZ",
        "finish": "Iced",
        "stock": 3,
        "rating": 4.9,
        "reviews_count": 19,
        "tags": ["iced", "arctic"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Full Iced Masterpiece",
        "slug": "full-iced-masterpiece",
        "category": "iced-out-grills",
        "price": 49999,
        "description": "Ultimate fully iced masterpiece design",
        "images": ["https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"],
        "material": "18K Gold",
        "teeth_count": 12,
        "gem_type": "Premium CZ",
        "finish": "Iced",
        "stock": 2,
        "rating": 5.0,
        "reviews_count": 15,
        "tags": ["iced", "masterpiece", "ultimate"],
        "featured": True,
        "bestseller": False
    },
    
    # Custom Grills (10 products)
    {
        "name": "Custom Single Grill",
        "slug": "custom-single-grill",
        "category": "custom-grills",
        "price": 7999,
        "description": "Personalized single tooth with your design",
        "images": ["https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"],
        "material": "Custom",
        "teeth_count": 1,
        "finish": "Custom",
        "stock": 50,
        "rating": 4.8,
        "reviews_count": 86,
        "tags": ["custom", "personalized"],
        "featured": True,
        "bestseller": True
    },
    {
        "name": "Name Engraved Grill",
        "slug": "name-engraved-grill",
        "category": "custom-grills",
        "price": 9999,
        "description": "Custom name engraving on premium grill",
        "images": ["https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"],
        "material": "Sterling Silver/Gold",
        "teeth_count": 2,
        "finish": "Engraved",
        "stock": 45,
        "rating": 4.9,
        "reviews_count": 92,
        "tags": ["custom", "engraved", "name"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Gemstone Custom Grill",
        "slug": "gemstone-custom-grill",
        "category": "custom-grills",
        "price": 12999,
        "description": "Custom design with your choice of gemstones",
        "images": ["https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"],
        "material": "Gold",
        "teeth_count": 2,
        "gem_type": "Custom Gems",
        "finish": "Polished",
        "stock": 40,
        "rating": 4.7,
        "reviews_count": 74,
        "tags": ["custom", "gemstone"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Gold Custom Grill",
        "slug": "gold-custom-grill",
        "category": "custom-grills",
        "price": 15999,
        "description": "Fully customizable gold grill design",
        "images": ["https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"],
        "material": "18K Gold",
        "teeth_count": 4,
        "finish": "Custom",
        "stock": 35,
        "rating": 4.8,
        "reviews_count": 68,
        "tags": ["custom", "gold"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Diamond Custom Grill",
        "slug": "diamond-custom-grill",
        "category": "custom-grills",
        "price": 19999,
        "description": "Custom diamond placement and design",
        "images": ["https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"],
        "material": "18K Gold",
        "teeth_count": 4,
        "gem_type": "Custom Diamonds",
        "finish": "Polished",
        "stock": 30,
        "rating": 4.9,
        "reviews_count": 61,
        "tags": ["custom", "diamond"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Artist Signature Grill",
        "slug": "artist-signature-grill",
        "category": "custom-grills",
        "price": 24999,
        "description": "Collaborate with our artists for unique design",
        "images": ["/custom-artist.jpg"],
        "material": "Premium",
        "teeth_count": 6,
        "finish": "Custom",
        "stock": 25,
        "rating": 5.0,
        "reviews_count": 54,
        "tags": ["custom", "artist", "signature"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Custom Elite Grill",
        "slug": "custom-elite-grill",
        "category": "custom-grills",
        "price": 29999,
        "description": "Elite custom design with premium materials",
        "images": ["https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"],
        "material": "Premium",
        "teeth_count": 6,
        "finish": "Custom",
        "stock": 20,
        "rating": 4.8,
        "reviews_count": 47,
        "tags": ["custom", "elite"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Luxury Custom Crown",
        "slug": "luxury-custom-crown",
        "category": "custom-grills",
        "price": 34999,
        "description": "Luxury crown design fully customizable",
        "images": ["https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"],
        "material": "18K Gold",
        "teeth_count": 8,
        "finish": "Custom",
        "stock": 15,
        "rating": 4.9,
        "reviews_count": 38,
        "tags": ["custom", "luxury", "crown"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Bespoke Diamond Grill",
        "slug": "bespoke-diamond-grill",
        "category": "custom-grills",
        "price": 44999,
        "description": "Fully bespoke diamond grill creation",
        "images": ["/custom-bespoke.jpg"],
        "material": "18K Gold",
        "teeth_count": 8,
        "gem_type": "Bespoke Diamonds",
        "finish": "Custom",
        "stock": 10,
        "rating": 5.0,
        "reviews_count": 32,
        "tags": ["custom", "bespoke", "diamond"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Ultimate Custom Masterpiece",
        "slug": "ultimate-custom-masterpiece",
        "category": "custom-grills",
        "price": 59999,
        "description": "Ultimate custom masterpiece - no limits",
        "images": ["/custom-ultimate.jpg"],
        "material": "Premium",
        "teeth_count": 12,
        "finish": "Custom",
        "stock": 5,
        "rating": 5.0,
        "reviews_count": 27,
        "tags": ["custom", "ultimate", "masterpiece"],
        "featured": True,
        "bestseller": False
    },
    
    # Teeth Gems (10 products)
    {
        "name": "Crystal Gem",
        "slug": "crystal-gem",
        "category": "teeth-gems",
        "price": 999,
        "description": "Classic crystal tooth gem",
        "images": ["/teeth-gems/grill-1.jpg"],
        "material": "Crystal",
        "gem_type": "Swarovski Crystal",
        "stock": 100,
        "rating": 4.7,
        "reviews_count": 145,
        "tags": ["gem", "crystal"],
        "featured": True,
        "bestseller": True
    },
    {
        "name": "Silver Gem",
        "slug": "silver-gem",
        "category": "teeth-gems",
        "price": 1299,
        "description": "Sterling silver tooth gem",
        "images": ["/teeth-gems/grill-2.jpg"],
        "material": "Sterling Silver",
        "stock": 90,
        "rating": 4.8,
        "reviews_count": 132,
        "tags": ["gem", "silver"],
        "featured": False,
        "bestseller": True
    },
    {
        "name": "Diamond Shine Gem",
        "slug": "diamond-shine-gem",
        "category": "teeth-gems",
        "price": 1999,
        "description": "Diamond-like shine tooth gem",
        "images": ["/teeth-gems/grill-3.jpg"],
        "material": "CZ Stone",
        "gem_type": "Cubic Zirconia",
        "stock": 85,
        "rating": 4.9,
        "reviews_count": 128,
        "tags": ["gem", "diamond"],
        "featured": True,
        "bestseller": True
    },
    {
        "name": "Heart Gem",
        "slug": "heart-gem",
        "category": "teeth-gems",
        "price": 1499,
        "description": "Heart-shaped crystal tooth gem",
        "images": ["/teeth-gems/grill-4.jpg"],
        "material": "Crystal",
        "gem_type": "Shaped Crystal",
        "stock": 75,
        "rating": 4.6,
        "reviews_count": 118,
        "tags": ["gem", "heart", "shaped"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Star Gem",
        "slug": "star-gem",
        "category": "teeth-gems",
        "price": 1499,
        "description": "Star-shaped crystal tooth gem",
        "images": ["/teeth-gems/grill-5.jpg"],
        "material": "Crystal",
        "gem_type": "Shaped Crystal",
        "stock": 70,
        "rating": 4.7,
        "reviews_count": 112,
        "tags": ["gem", "star", "shaped"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Butterfly Gem",
        "slug": "butterfly-gem",
        "category": "teeth-gems",
        "price": 1799,
        "description": "Butterfly-shaped premium tooth gem",
        "images": ["/teeth-gems/grill-6.jpg"],
        "material": "Crystal",
        "gem_type": "Shaped Crystal",
        "stock": 65,
        "rating": 4.8,
        "reviews_count": 105,
        "tags": ["gem", "butterfly", "shaped"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Luxury Gem Pack",
        "slug": "luxury-gem-pack",
        "category": "teeth-gems",
        "price": 2499,
        "description": "Pack of 5 assorted luxury tooth gems",
        "images": ["/teeth-gems/grill-7.jpg"],
        "material": "Mixed",
        "gem_type": "Assorted",
        "stock": 60,
        "rating": 4.9,
        "reviews_count": 98,
        "tags": ["gem", "pack", "luxury"],
        "featured": True,
        "bestseller": True
    },
    {
        "name": "Premium Diamond Gem",
        "slug": "premium-diamond-gem",
        "category": "teeth-gems",
        "price": 3499,
        "description": "Premium diamond tooth gem",
        "images": ["/teeth-gems/grill-8.jpg"],
        "material": "Gold Setting",
        "gem_type": "Real Diamond",
        "stock": 50,
        "rating": 5.0,
        "reviews_count": 87,
        "tags": ["gem", "diamond", "premium"],
        "featured": True,
        "bestseller": False
    },
    {
        "name": "Custom Gem Design",
        "slug": "custom-gem-design",
        "category": "teeth-gems",
        "price": 4999,
        "description": "Custom designed tooth gem",
        "images": ["/teeth-gems/grill-9.jpg"],
        "material": "Custom",
        "gem_type": "Custom",
        "stock": 40,
        "rating": 4.8,
        "reviews_count": 76,
        "tags": ["gem", "custom"],
        "featured": False,
        "bestseller": False
    },
    {
        "name": "Signature Luxury Gem",
        "slug": "signature-luxury-gem",
        "category": "teeth-gems",
        "price": 6999,
        "description": "Signature luxury tooth gem collection",
        "images": ["/teeth-gems/grill-10.jpg"],
        "material": "Gold",
        "gem_type": "Premium Mix",
        "stock": 30,
        "rating": 5.0,
        "reviews_count": 64,
        "tags": ["gem", "signature", "luxury"],
        "featured": True,
        "bestseller": False
    }
]

CATEGORIES_DATA = [
    {
        "id": "silver-grills",
        "name": "Silver Grills",
        "slug": "silver-grills",
        "description": "Premium sterling silver grills for a classic look",
        "image": "https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"
    },
    {
        "id": "gold-grills",
        "name": "Gold Grills",
        "slug": "gold-grills",
        "description": "Luxury 18K gold grills for the bold",
        "image": "https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"
    },
    {
        "id": "diamond-grills",
        "name": "Diamond Grills",
        "slug": "diamond-grills",
        "description": "Premium diamond grills for maximum shine",
        "image": "https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"
    },
    {
        "id": "iced-out-grills",
        "name": "Iced Out Grills",
        "slug": "iced-out-grills",
        "description": "Fully iced grills with brilliant sparkle",
        "image": "https://images.pexels.com/photos/19060654/pexels-photo-19060654.jpeg"
    },
    {
        "id": "custom-grills",
        "name": "Custom Grills",
        "slug": "custom-grills",
        "description": "Design your own custom grill masterpiece",
        "image": "https://images.pexels.com/photos/772850/pexels-photo-772850.jpeg"
    },
    {
        "id": "teeth-gems",
        "name": "Teeth Gems",
        "slug": "teeth-gems",
        "description": "Dazzling tooth gems for subtle elegance",
        "image": "https://images.pexels.com/photos/8964508/pexels-photo-8964508.jpeg"
    }
]
